version: 2.1

orbs:
  flutter: circleci/flutter@2.0.0
  fastlane: circleci/fastlane

jobs:
  deploy:
    executor:
      name: macos/default
      shell: /bin/bash
    steps:
      - checkout

      - fastlane/install

      - flutter/install_pub:
          cache-version: v1

      - run:
          name: Flutter pub get
          command: flutter pub get

#       - run:
#           name: Build iOS
#           command: flutter build ios --release --no-codesign

#       - fastlane/run:
#           lane: deploy_to_testflight  # Corrected lane name

# workflows:
#   version: 2
#   build_ios:
#     jobs:
#       - deploy
