version: 2.1

orbs:
  flutter: circleci/flutter@0.1.0
  fastlane: circleci/fastlane@0.3.0

jobs:
  deploy:
    executor:
      name: macos/default
      shell: /bin/bash
    steps:
      - checkout

      - fastlane/install

      - flutter/install_pub:
          cache-version: v1

      - run:
          name: Flutter pub get
          command: flutter pub get

      - run:
          name: Build iOS
          command: flutter build ios --release --no-codesign

      - fastlane/run:
          lane: dep_to_testflight
workflows:
  version: 2
  build_ios:
    jobs:
      # - build_android
      - deploy