# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 15.0.0
    environment:
      FL_OUTPUT_DIR: /Users/distiller/
      FASTLANE_LANE: upload_testflight
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: cd ios && bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: /Users/distiller/
      - store_test_results:
          path: /Users/distiller/

  adhoc:
    macos:
      xcode: 15.0.0
    environment:
      FL_OUTPUT_DIR: /Users/distiller/
      FASTLANE_LANE: upload_testflight
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: cd ios && bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: /Users/distiller/

workflows:
  build-test-adhoc:
    jobs:
      - build-and-test
      - adhoc:
          filters:
            branches:
              only: main
          requires:
            - build-and-test
