default_platform(:ios)

platform :ios do
  desc "Build and deploy the Flutter app to the App Store"
  lane :build_and_deploy do
    cocoapods
    gym(
      scheme: "Runner",  # Replace with your actual scheme name
      export_method: "app-store",
      configuration: "Release"
    )

    deliver(
      username: ENV["FASTLANE_USER"],
      app_identifier: "com.instacoach.coachmanager",
      ipa: "/Users/distiller/project/build/ios/iphoneos/Runner.app",
      skip_deploy: true
    )
  end
end
