-----BEGIN PRIVATE KEY-----/n
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgyTRf5TOR2UV7OVj/
FiGz+fuwrM0hUPBuw4fPpXPp9QmgCgYIKoZIzj0DAQehRANCAAR0xJPRO/Or8LNI
COHAe55Mvjtn5tiyjO2zijra87w+7RJcqhMGRhkHqCtbws6sowwgJFdXeUasuRPX
/RsFEmxj/n
-----END PRIVATE KEY-----