lane :build_and_sign do
  # Your other build actions go here

  # Set the development team
  build_app(
    scheme: "Runner",
    export_method: "app-store", # or other export methods
    build_path: "/Users/distiller/project/build/ios/iphoneos/Runner.app",
    skip_profile_detection: true, # Set this to true if you want to skip automatic profile detection
    team_id: "J6Q6Y9VYC4@icloud.com", # Specify your development team identifier
    export_options: {
      compileBitcode: false, # Adjust export options as needed
      uploadBitcode: false,
      uploadSymbols: true
    }
  )

  # Your other actions go here
end

lane :your_deploy_lane do
  produce(
    # username: "J6Q6Y9VYC4@icloud.com", # Your Apple ID
    app_identifier: "com.instacoach.coachmanager",
    username: "admin@instacoach.com"
  )
  # build_app(xcargs: "-allowProvisioningUpdates")
  increment_build_number  # Increment the build number
  set_development_team
  build_ios_app           # Build the iOS app
  upload_to_testflight    # Upload to TestFlight
  # Your deployment steps go here
end

platform :ios do
    lane :beta do
      # build_app(xcargs: "-allowProvisioningUpdates")
      increment_build_number  # Increment the build number
      set_development_team
      build_ios_app(xcargs: "-allowProvisioningUpdates")            # Build the iOS app
      upload_to_testflight    # Upload to TestFlight
    end
    lane :set_development_team do
      project_path = Dir["*.xcodeproj"].first
      update_project_team(
        path: project_path,
        teamid:"J6Q6Y9VYC4"
      )
    end
  
  end