# fastlane/Fastfile

default_platform(:ios)

platform :ios do
  lane :build_and_deploy_to_testflight do
    increment_build_number

    gym(
      scheme: "Runner",
      export_method: "app-store",
      configuration: "Release",
      export_options: {
        provisioningProfiles: {
          "com.instacoach.coachmanager" => "instacoach"
        }
      }
    )

    pilot(
      distribute_external: true,
      notify_external_testers: true,
      groups: ["YourTestFlightGroup"],
      changelog: "Release notes for this build."
    )
  end
end
