default_platform(:ios)

platform :ios do
  desc "Build and release a new version to the App Store"
  lane :release do
    match(type: "appstore")
    gym(export_method: "app-store")
    pilot(skip_submission: true)
    pilot(ipa: ENV['CIRCLE_ARTIFACTS'] + "/ipa/Runner.ipa")
  end
end